node('SLAVE') {

    stage('Code Check-Out'){
        git 'https://github.com/Mahen0727/studentapp-ui.git'
    }

    stage("Compile") {
        sh '''
mvn compile
'''
    }
    
    stage("Build") {
        sh '''
mvn package
'''
    }

    stage("Upload Artifacts") {
        sh '''
mvn deploy
'''
    }
    
}
//