node('SLAVE') {

    stage('Code Check-Out'){
        git 'https://github.com/Mahen0727/studentapp-ui.git'
    }

    stage("Compile") {
        sh '''
mvn compile
'''
    }
    
    stage("Build") {
        sh '''
mvn package
'''
    }

    stage("Upload Artifacts") {
        sh '''
mvn deploy
'''
    }

    stage('Test') {
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'TERRAFORM-CREDENTIALS ',
    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {

    sh 'echo uname=$USERNAME pwd=$PASSWORD'
    export AWS_ACCESS_KEY_ID="$USERNAME"
    export AWS_SECRET_ACCESS_KEY="$PASSWORD"
    }
}


}
//