node('SLAVE') {

    stage('Code Check-Out'){
       dir('DEVELOPMENT'){
        git 'https://github.com/Mahen0727/studentapp-ui.git'
       }
    }

    stage("Compile") {
         dir('DEVELOPMENT'){
        sh '''
        mvn compile
        '''
        }
    }
    
    stage("Build") {
         dir('DEVELOPMENT'){
        sh '''
        mvn package
        '''
         }
    }

    stage('Create-Test-Environement') {

    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'TERRAFORM-CREDENTIALS ',
    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
    dir('TERRAFORM'){
        git 'https://github.com/Mahen0727/Terraform.git' 
        sh '''
        echo uname=$USERNAME pwd=$PASSWORD
        export AWS_ACCESS_KEY_ID="$USERNAME"
        export AWS_SECRET_ACCESS_KEY="$PASSWORD"
        cd 09-test-s3-bucket-creation
        terraform init
        terraform apply
        '''
        }
    }
    }
}
//